// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS3_z98Gl0BdC6spRTaKenatfP4P0OIdQ',
    appId: '1:575386239839:web:11673ff0cf91552cec6cea',
    messagingSenderId: '575386239839',
    projectId: 'my-school-a24a6',
    authDomain: 'my-school-a24a6.firebaseapp.com',
    storageBucket: 'my-school-a24a6.appspot.com',
    measurementId: 'G-ZBT7V95976',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOjN0sp4wyWNf8fkgabUHEfWlyhg5Ab2M',
    appId: '1:575386239839:android:49e1325d346fc519ec6cea',
    messagingSenderId: '575386239839',
    projectId: 'my-school-a24a6',
    storageBucket: 'my-school-a24a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKOF9Fu8IlKXBNIJVQ9F3Up1XfxCPvP5U',
    appId: '1:575386239839:ios:c34b665a65e9f0f4ec6cea',
    messagingSenderId: '575386239839',
    projectId: 'my-school-a24a6',
    storageBucket: 'my-school-a24a6.appspot.com',
    iosBundleId: 'com.example.mySchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKOF9Fu8IlKXBNIJVQ9F3Up1XfxCPvP5U',
    appId: '1:575386239839:ios:c34b665a65e9f0f4ec6cea',
    messagingSenderId: '575386239839',
    projectId: 'my-school-a24a6',
    storageBucket: 'my-school-a24a6.appspot.com',
    iosBundleId: 'com.example.mySchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS3_z98Gl0BdC6spRTaKenatfP4P0OIdQ',
    appId: '1:575386239839:web:34b49e8196a132d6ec6cea',
    messagingSenderId: '575386239839',
    projectId: 'my-school-a24a6',
    authDomain: 'my-school-a24a6.firebaseapp.com',
    storageBucket: 'my-school-a24a6.appspot.com',
    measurementId: 'G-1HXBL350B6',
  );
}
